# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py314"

line-length = 256

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    "FBT001", # don't care about positional bool arguments
    "FBT003", # don't care about positional bool arguments
    "TRY003", # long messages for exceptions are fine
    "D101", # doc strings are optional
    "D102", # doc strings are optional
    "D103", # doc strings are optional
    "D107", # doc strings for __init__ are optional
    "TC001", # imports that only exist for type checking should always be there to reduce code complexity
    "TC002", # imports that only exist for type checking should always be there to reduce code complexity
    "TC003", # imports that only exist for type checking should always be there to reduce code complexity
    "EM101", # no need to asign exception strings to variables first
    "PLR0913", # congnitive complexity here is fine
    "S104", # yes, we want to bind to all interfaces
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.per-file-ignores]
"tests/**/*.py" = [
    "S101", # asserts allowed in tests...
    "PLR2004", # magic numbers are allowed in tests
    "D103", # doc strings are not mandatorry for tests since the test name should be descriptive
]
